# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz &&
      tar xf cloudflared-stable-linux-amd64.tgz &&
      sudo service ssh start &&
      wget -qO - https://nim-lang.org/choosenim/init.sh | sh
    command: echo 'start script'
